In [1]:
import numpy as np 

In [2]:
list_ = ['1','2','3','4','5']

In [4]:
array_list = np.array(object = list_)

In [5]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

#Ans.1

In [6]:
type(list_)

list

In [7]:
type(array_list)

numpy.ndarray

yes, there is a difference in the data types of variables 'list_' and 'array_list'. 

The variable 'list_' is a python list, which can contain elements of any data type. In tis case, it contains strings("1","2","3","4","5").

The variable 'array_list' is NumPy array created from the 'list_' variable. when you create a NumPy array, it automatically converts the elements to a common data type based on the input values.In this case, since all the elements in 'list_' are strings, the 'array_list' will be NumPy array of strings 

#Ans.2

In [8]:
for element in list_:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [9]:
for element in array_list:
    print(type(element))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


#Ans.3

In [10]:
array_list = np.array(list_ , dtype=int)

In [11]:
for element in list_:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [12]:
for element in array_list:
    print(type(element))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


#Ans.4

In [13]:
num_list = [[1,2,3],[4,5,6]]
num_array = np.array(num_list)

In [15]:
num_array = np.array(num_list)

In [16]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
num_array.shape

(2, 3)

In [18]:
num_array.size

6

#Ans.5

In [22]:
arr5 = np.zeros((3,3))

In [23]:
arr5

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#Ans.6

In [24]:
identity_matrix = np.eye(5)

In [25]:
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])